### ISSUE TITLE
inbo_slides returned empty toc

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#66] opened 2020-09-16 09:05 UTC
While recompiling https://github.com/inbo/tutorials/blob/3231eda/content/tutorials/r_inla/spatial/index.Rmd (because of updating CRS specifications in the tutorials repo), an empty TOC slide was returned in the resulting PDF:

![afbeelding](https://user-images.githubusercontent.com/19164640/93315449-5dc8f080-f80b-11ea-9d59-60cf20b62352.png)

I worked around it (in inbo/tutorials@3dd5f6e) by using INBOmd at 32cd4eb, though clearly this is unwanted.

**Comment by ElsLommelen** [comment] 2021-04-06 12:04
The same occurs when choosing this template for a new slideshow.  When `slide_level` is not changed (default 1 is kept) and `toc` is set to TRUE, the slide titled 'Overzicht' is completely empty.  When `slide_level` is changed to 2, the numbers 1, 2 and 3 appear, similar to the example of @florisvdh, but without the squares (maybe he used slide_level 3?).  When moving near these numbers, I noticed there is a link referring to the 1st level title slides.  Maybe the text is there but invisible?

Personally I would prefer that the toc shows the content up to the same level as indicated in slide_level, so 2 levels in my case, now this seems not to be the case.

**Comment by ThierryO** [comment] 2021-04-08 08:18
Toc text was white, hence not visible. It should be fixed in 7239a82.

`toc: TRUE` only define whether you want a toc or not. Using `slide_level: 1`, you have no sections, hence an empty toc. That is a feature, not a bug.

**Closed** 2021-09-04 15:12 UTC
Labels: bug
